version: "3.8"

services:
  smeargle-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
      - ./internal/scripts:/app/internal/scripts
    environment:
      - ENV=development